[package]
name = "octane"
version = "0.1.0"
authors = ["weegee <somilsharma627@gmail.com>", "aplet123 <aplet@aplet.me>"]
edition = "2018"

[dependencies]
lazy_static = "1.4.0"
rustls = { version = "0.17.0", optional = true }
tokio = { version = "0.2.21", features = ["tcp", "fs", "stream", "macros", "io-util"] }
futures = "0.3"

[dependencies.macros]
path = "macros"

[features]
default = ["faithful", "query_strings"]
faithful = []
raw_headers = []
query_strings = []
extended_queries = []
https = ["rustls"]

[workspace]
members = [
    "macros"
]
