[package]
name = "octane"
version = "0.1.0"
authors = ["weegee <somilsharma627@gmail.com>", "aplet123 <aplet@aplet.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
rustls = "0.17.0"
smol = "0.1.4"
futures = "0.3"

[features]
default = ["faithful", "query_strings"]
faithful = []
raw_headers = []
query_strings = []
